version: '3.7'

services:
  app:
    image: nginx:1.16.1
    ports:
      - "8080:80"
    volumes:
      - ./app:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    container_name: php74-1
    build: './docker/php-fpm'
    volumes:
      - ./app:/application
      - ./docker/php-fpm/xdebug.ini:/etc/php/7.4/fpm/conf.d/xdebug.ini'
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    ports:
      - "9001:9000"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
      - rabbitmq:/var/log/rabbitmq
  mysql:
    image: 'mysql:8.0'
    working_dir: /application
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'

  elasticsearch:
    container_name: es-container-1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    volumes:
      - ./docker-volumes/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container-1
    image: docker.elastic.co/kibana/kibana:7.1.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
volumes:
  rabbitmq:
